### PR TITLE
Move repo size information to the repo details bar

### LINKED ISSUE #50: Support new repository page
Github is previewing a new look for the repository page (enable it by going to Avatar  → feature preview  → Repository Refresh), which isn't compatible with the extension.

Screen Shot 2020-06-18 at 1 15 35 AM

### LINKED ISSUE #60: Position of size label on the screen
Tracking position related changes here in this issue @guidezpl

### PR DESCRIPTION
**Pull request by guidezpl**
Updates the location of the main link
Changes the link to a button for better accessibility
Fixes dirSize using ... instead of ··· when loading
Clears dir cursor and title after loading

image

Also updates the screenshot image

Closes #50
Closes #60

### CODE REVIEW

**Comment by guidezpl** [comment]
@harshjv friendly ping :)

**Comment by harshjv** [comment]
@guidezpl Thanks for the PR!

I think Github has updated the UI again. For instance, `Go to file` button is on the same line with branch selector.

Can you update your PR for the new UI?

**Comment by guidezpl** [comment]
Done!

**Comment by goldbattle** [comment]
Any update on merging this?
Would be really nice to have with the current github UI.
Thanks!

**Comment by guidezpl** [comment]
@harshjv Update on this?

**Comment by guidezpl** [comment]
Updated for latest UI, this can be merged

**Comment by guidezpl** [comment]
seems like abandonware, closing

**Pull request closed without merging**
