### PR TITLE
Fixed Aesthetics

### PR DESCRIPTION
**Pull request by jtran4481**
Fixed the aesthetics including color and the null tooltip.

### CODE REVIEW

**Comment by guidezpl** [comment]
@harshjv this looks good, can you please merge? :)

**Comment by jtran4481** [comment]
Ah, I don't have write access.

**Comment by harshjv** [comment]
Thanks for the PR. I am addressing #50 currently. Want to help there?

**Comment by harshjv** [comment]
Adressed in https://github.com/harshjv/github-repo-size/commit/72041e354a2cf4d60f2a50b5791d3857558305e6

**Pull request closed without merging**
